### ISSUE TITLE
After transferring 0.3 eth from Ethereum to StarkNet, I have the updated balance on Ethereum but still no money on StarkNet

### ISSUE THREAD

**Issue by NitzanGrossman** [starkware-libs/starkgate-frontend#33]

**Comment by NitzanGrossman** [comment]
Might be worth to have a pop-up notification saying the new balance takes (a certain amount of) time and also where can the data be monitored

**Comment by dan-ziv** [comment]
@bbrandtom not sure it's really an issue?

**Comment by dan-ziv** [comment]
relates to https://github.com/starkware-libs/starkgate-frontend/issues/47
