### ISSUE TITLE
Allow changing the MetaMask account after one has been selected.

### ISSUE THREAD

**Issue by gkaempfer** [starkware-libs/starkgate-frontend#59]
**Describe the bug**
You select an account on MetaMask and connect it to the web page. There seems to be no way to change the account (it remains fixed on the webpage even if you switch accounts on MetaMask).

**Expected behavior**
Allow switching / deleting a selected account on the page for reselection via MetaMask.

**Comment by dan-ziv** [comment]
Can't reproduce the issue.
See attached video.

https://user-images.githubusercontent.com/21081590/148991987-72949046-a5c9-416f-9eb2-d9f8a3b279b2.mp4

**Comment by dan-ziv** [comment]
Handled in
https://github.com/starkware-libs/starkgate-frontend/pull/176
